# Generated by Django 5.2.11 on 2026-02-24 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.deposit')),
            ],
            options={
                'db_table': 'referral_commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
