# Generated by Django 5.2.11 on 2026-03-04 23:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_withdrawalfeepayment_options'),
        ('referrals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Total Commission Earned (USDT)')),
                ('total_referrals', models.IntegerField(default=0, verbose_name='Total Users Referred')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Commission Summary',
                'verbose_name_plural': 'Admin Commission Summaries',
                'db_table': 'admin_commission_summary',
            },
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='is_paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='paid_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('reversed', 'Reversed')], default='credited', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='referralcommission',
            unique_together={('deposit', 'referrer')},
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referrer'], name='referral_co_referre_31d978_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referee'], name='referral_co_referee_8b3eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['-created_at'], name='referral_co_created_99b229_idx'),
        ),
        migrations.AddField(
            model_name='admincommissionsummary',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summary', to=settings.AUTH_USER_MODEL),
        ),
    ]
