# Generated by Django 5.1.9 on 2026-03-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_add_referral_code_used_and_commission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcommission',
            name='tier',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mining Tier'),
        ),
    ]
