# Generated by Django 5.1.7 on 2026-05-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_referraldeposit_referralwithdrawal_and_more'),
        ('referrals', '0004_referralcommission_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.deposit'),
        ),
    ]
