# Generated by Django 5.2.11 on 2026-02-24 18:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveIntegerField()),
                ('amount_usdt', models.DecimalField(decimal_places=8, max_digits=12)),
                ('amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('mined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mining Earning',
                'verbose_name_plural': 'Mining Earnings',
                'db_table': 'mining_earnings',
                'ordering': ['-mined_at'],
            },
        ),
        migrations.CreateModel(
            name='MiningTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earn_per_24h_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('withdrawal_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Withdrawal Fee (USD)')),
            ],
            options={
                'verbose_name': 'Mining Tier',
                'verbose_name_plural': 'Mining Tiers',
                'db_table': 'mining_tiers',
                'ordering': ['tier_number'],
            },
        ),
        migrations.CreateModel(
            name='UserMiningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mining Session',
                'verbose_name_plural': 'Mining Sessions',
                'db_table': 'user_mining_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
