# Generated by Django 5.2.11 on 2026-02-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miningearning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userminingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
