# Generated by Django 5.1.9 on 2026-03-09 22:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_update_plan5_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningtier',
            name='referral_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Referral Reward (USDT)'),
        ),
    ]
