# Generated by Django 5.2.11 on 2026-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Withdrawal Fee Paid'),
        ),
    ]
