# Generated by Django 5.2.11 on 2026-02-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_withdrawal_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_mined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Mining Time'),
        ),
    ]
