# Generated by Django 5.2.11 on 2026-02-26 08:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_mined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='agent_account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agent Account Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agent Account Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agent Bank Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Agent Commission %'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_wallet_usdt',
            field=models.CharField(blank=True, max_length=120, verbose_name='Agent USDT Wallet'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Is Agent'),
        ),
    ]
