# Generated by Django 5.2.11 on 2026-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverificationcode_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Super Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10, verbose_name='Admin Application Status'),
        ),
    ]
