# Generated by Django 5.2.11 on 2026-03-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_admin_status_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Admin Application',
                'verbose_name_plural': '⚠️ Pending Admin Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=8, verbose_name='Referral Code Used at Signup'),
        ),
    ]
