# Generated by Django 5.2.11 on 2026-03-04 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_referral_code_used_and_commission_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id_raw', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('admin_approved', 'Admin Application Approved'), ('admin_rejected', 'Admin Application Rejected'), ('admin_deactivated', 'Admin Deactivated'), ('admin_reactivated', 'Admin Reactivated'), ('admin_deleted', 'Admin Deleted'), ('commission_credited', 'Commission Credited'), ('commission_reversed', 'Commission Reversed'), ('referral_created', 'Referral Registered'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('fee_approved', 'Withdrawal Fee Approved'), ('settings_changed', 'Global Settings Changed'), ('login', 'Admin Login')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['actor_id_raw'], name='audit_logs_actor_i_c0ab2f_idx'), models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx')],
            },
        ),
    ]
