# Generated by Django 5.1.9 on 2026-03-09 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_admin_invitation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_balance_usdt',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Referral Balance (USDT)'),
        ),
    ]
