# Generated by Django 6.0.2 on 2026-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_referral_balance_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_telegram_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Agent Telegram Link'),
        ),
    ]
