# Generated by Django 5.1.7 on 2026-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_agent_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_telegram',
            field=models.BooleanField(default=False, verbose_name='Joined Telegram Community'),
        ),
    ]
