# Generated by Django 5.2.11 on 2026-02-24 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_target', models.IntegerField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('method', models.CharField(choices=[('crypto', 'USDT TRC20'), ('bank', 'Bank Transfer (NGN)')], max_length=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'db_table': 'deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ngn', models.DecimalField(decimal_places=2, default=1600, max_digits=10)),
                ('usd_to_ghs', models.DecimalField(decimal_places=2, default=15.5, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_wallet', models.CharField(default='TQnXpzuRr8PFRnKqDU5b7ZfmwdJGFH4kLm', max_length=120)),
                ('bank_name', models.CharField(default='Opay', max_length=100)),
                ('account_name', models.CharField(default='Apex Mining Ltd', max_length=200)),
                ('account_number', models.CharField(default='0123456789', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payment_settings',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=12)),
                ('amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('wallet_address', models.CharField(max_length=120)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
