# Generated by Django 5.2.11 on 2026-02-25 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalFeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveIntegerField(verbose_name='Plan Tier')),
                ('fee_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('crypto', 'Crypto'), ('bank', 'Bank')], max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='withdrawal_fees/')),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Fee Payment',
                'verbose_name_plural': 'Withdrawal Fee Payments',
                'db_table': 'withdrawal_fee_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
