# Generated by Django 5.2.11 on 2026-02-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_withdrawalfeepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='tx_hash',
            new_name='account_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='admin_note',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('bank', 'Bank')], default='crypto', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount_usdt',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
