# Generated by Django 5.2.11 on 2026-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_tx_hash_withdrawal_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='support_alt_url',
            field=models.URLField(blank=True, default='', help_text='Optional secondary support link', max_length=500),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='support_url',
            field=models.URLField(blank=True, default='', help_text='Primary support link (e.g. Telegram, WhatsApp, email, or helpdesk URL)', max_length=500),
        ),
    ]
