# Generated by Django 6.0.2 on 2026-03-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentsettings_support_alt_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalfeepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transfer Fee Payment', 'verbose_name_plural': 'Transfer Fee Payments'},
        ),
    ]
