# Generated by Django 5.1.9 on 2026-03-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_withdrawalfeepayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='is_referral',
            field=models.BooleanField(default=False, verbose_name='Is Referral Withdrawal'),
        ),
    ]
