# Generated by Django 5.1.9 on 2026-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_withdrawal_is_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDeposit',
            fields=[
            ],
            options={
                'verbose_name': 'Referral Activity (Deposit)',
                'verbose_name_plural': 'Referral Activity (Deposits)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.deposit',),
        ),
        migrations.CreateModel(
            name='ReferralWithdrawal',
            fields=[
            ],
            options={
                'verbose_name': 'Referral Activity (Withdrawal)',
                'verbose_name_plural': 'Referral Activity (Withdrawals)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.withdrawal',),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='telegram_community_url',
            field=models.URLField(blank=True, default='https://t.me/apexcloudmining', help_text='Link to the official Telegram community channel', max_length=500),
        ),
    ]
