# Generated by Django 5.1.7 on 2026-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_referraldeposit_referralwithdrawal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='referral_bonus_usdt',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='USDT reward credited to referrer for each successful sign-up', max_digits=8),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='telegram_gate_url',
            field=models.URLField(blank=True, default='https://t.me/apexcloudmining', help_text='Telegram link used in the Join Telegram gate page (after registration)', max_length=500),
        ),
    ]
